export const E_TOKEN_EXPIRED = 'E_TOKEN_EXPIRED';
export const E_TOKEN_INVALID = 'E_TOKEN_INVALID';
export const E_UNAUTHORIZED  = 'E_UNAUTHORIZED';

export const E_USER_NOT_FOUND = 'E_USER_NOT_FOUND';
export const E_INVALID_PASSWORD = 'E_INVALID_PASSWORD';
export const E_USER_BLOCKED = 'E_USER_BLOCKED';

export const E_DONT_HAVE_PERMISSION = 'DO_NOT_HAVE_PERMISSION';

export const E_INTERNAL_SERVER_ERROR = 'E_INTERNAL_SERVER_ERROR';
export const E_INVALID_DATA = 'E_INVALID_DATA';
export const E_REQUEST_BODY_INVALID = 'E_REQUEST_BODY_INVALID';
export const E_NOT_FOUND = 'E_NOT_FOUND';
